;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-semi&comma
        end-of-visual-line
        kill-visual-line
        mc/mark-next-line-like-this
        org-beginning-of-line
        org-end-of-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
