;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        TeX-insert-dollar
        TeX-insert-sub-or-superscript
        beginning-of-visual-line
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        dabbrev-expand
        delete-horizontal-space
        electric-newline-and-maybe-indent
        end-of-visual-line
        helm-confirm-and-exit-minibuffer
        indent-for-tab-command
        kill-visual-line
        mark-whole-buffer
        markdown-insert-bold
        mc/mark-next-line-like-this
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-metaright
        org-self-insert-command
        org-shiftmetaright
        org-yank
        other-frame
        sgml-close-tag
        sgml-slash
        slime-autodoc-space
        string-rectangle
        transpose-words
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        dired-unmark-backward
        markdown-exdent-or-delete
        ))
